# Generated by Django 3.2.9 on 2021-11-20 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('modea_base', models.CharField(choices=[('USD', 'Dolar'), ('EUR', 'Euro'), ('JPY', 'Iene')], default='USD', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
    ]
