# Generated by Django 3.2.9 on 2021-11-21 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='modea_base',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dolar'), ('JPY', 'Iene')], default='USD', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
