# Generated by Django 3.2.9 on 2021-11-22 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes_app', '0002_alter_cotacao_modea_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='modea_base',
        ),
        migrations.AddField(
            model_name='cotacao',
            name='moeda_base',
            field=models.CharField(choices=[('BRL', 'Real'), ('JPY', 'Iene'), ('EUR', 'Euro')], default='BRL', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='data_final',
            field=models.DateField(help_text='Por favor, use o seguinte formato: <em>DD/MM/YYYY</em>.'),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='data_inicial',
            field=models.DateField(help_text='Por favor, use o seguinte formato: <em>DD/MM/YYYY</em>.'),
        ),
    ]
