# Generated by Django 3.2.9 on 2021-11-22 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes_app', '0003_auto_20211121_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('moeda_cotada', models.CharField(choices=[('BRL', 'Real'), ('EUR', 'Euro'), ('JPY', 'Iene')], max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='moeda_base',
        ),
        migrations.AddField(
            model_name='cotacao',
            name='moeda_a_ser_cotada',
            field=models.CharField(choices=[('BRL', 'Real'), ('EUR', 'Euro'), ('JPY', 'Iene')], default='BRL', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
