# Generated by Django 3.2.9 on 2021-11-22 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes_app', '0004_auto_20211121_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaoapi',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='cotacaoapi',
            constraint=models.UniqueConstraint(fields=('data', 'moeda_cotada'), name='cotacao_unica_moeda_dia'),
        ),
    ]
